services:
  - type: web
    name: mp-board-paper-predictor
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DB_PATH
        value: "/tmp/db.sqlite3"
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false
