# Generated by Django 4.2.30 on 2026-04-20 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_class', models.CharField(help_text='e.g., 10th or 12th', max_length=50)),
                ('subject', models.CharField(help_text='e.g., Science (विज्ञान)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='uploads/papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_raw_text', models.TextField(blank=True, help_text='Raw OCR output from Sarvam API', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='analyzer.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_2_deduplicated_json', models.JSONField(blank=True, help_text='Output from Gemini Stage 2', null=True)),
                ('stage_3_dl_insights_json', models.JSONField(blank=True, help_text='Output from Gemini Stage 3', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analyzer.analysissession')),
            ],
        ),
    ]
