# Generated by Django 4.2.30 on 2026-04-26 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., MP Board Class 10th Science 2024', max_length=200)),
                ('title_hindi', models.CharField(blank=True, help_text='e.g., कक्षा 10वीं विज्ञान 2024', max_length=200)),
                ('student_class', models.CharField(choices=[('10th', 'Class 10th'), ('12th', 'Class 12th')], max_length=10)),
                ('subject', models.CharField(choices=[('Science', 'Science / विज्ञान'), ('Maths', 'Maths / गणित'), ('Hindi', 'Hindi / हिंदी'), ('English', 'English / अंग्रेजी'), ('SocialScience', 'Social Science / सामाजिक विज्ञान'), ('Physics', 'Physics / भौतिकी'), ('Chemistry', 'Chemistry / रसायन विज्ञान'), ('Biology', 'Biology / जीव विज्ञान')], max_length=100)),
                ('year', models.CharField(help_text='e.g., 2024', max_length=10)),
                ('set_name', models.CharField(blank=True, help_text='e.g., Set A', max_length=20)),
                ('total_marks', models.IntegerField(default=80)),
                ('pdf_file', models.FileField(upload_to='library/papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from students')),
            ],
            options={
                'verbose_name': 'Library Paper',
                'verbose_name_plural': 'Library Papers',
                'ordering': ['-year', 'subject'],
            },
        ),
        migrations.AlterModelOptions(
            name='analysissession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='analysissession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='stage_2_deduplicated_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='stage_3_dl_insights_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='student_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/papers/'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='library_paper',
            field=models.ForeignKey(blank=True, help_text='Pre-loaded library paper used for this analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyzer.librarypaper'),
        ),
    ]
