# Generated by Django 4.2.30 on 2026-04-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_librarypaper_alter_analysissession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='error_message',
            field=models.TextField(blank=True, help_text='Stores the error if the pipeline fails', null=True),
        ),
    ]
