# Generated by Django 4.2.30 on 2026-05-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_analysissession_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='extracted_questions_json',
            field=models.JSONField(blank=True, help_text='JSON list of questions extracted from this paper', null=True),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('extracting', 'Extracting Papers (Sarvam AI)'), ('analyzing', 'Analyzing with AI (Gemini)'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='librarypaper',
            name='pdf_file',
            field=models.FileField(help_text='Upload PDF or Image (.jpg, .png)', upload_to='library/papers/'),
        ),
    ]
