# Generated by Django 4.2.30 on 2026-05-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_exampaper_extracted_questions_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampaper',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='library_paper',
            field=models.ForeignKey(default=1, help_text='Pre-loaded library paper used for this analysis', on_delete=django.db.models.deletion.CASCADE, to='analyzer.librarypaper'),
            preserve_default=False,
        ),
    ]
