# Generated by Django 4.2.30 on 2026-05-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_remove_exampaper_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarypaper',
            name='is_active',
        ),
    ]
