# Generated by Django 4.2.30 on 2026-05-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_remove_librarypaper_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarypaper',
            options={'ordering': ['-year', 'subject']},
        ),
        migrations.RemoveField(
            model_name='analysissession',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='exampaper',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='librarypaper',
            name='student_class',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='librarypaper',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
